name: Python Package Unittest

on: [push]

jobs:
  unittest-linux:
    runs-on: self-hosted
    strategy:
      max-parallel: 5
    needs: build-linux
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: wcsimdatatools
#        miniconda-version: "latest"
        environment-file: env.yaml
        python-version: 3.10.3
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Test with unittest
      run: |
        python -m unittest discover -s ./tests  -p 'test_*.py'