name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: self-hosted
    strategy:
      max-parallel: 5
#    defaults:
#      run:
#        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: wcsimdatatools
#        miniconda-version: "latest"
        environment-file: env.yaml
        python-version: 3.10.3
        auto-activate-base: false
        remove-profiles: false # very important to avoid profiles deletion
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
#    - name: Lint with flake8
#      run: |
#        conda install flake8
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install .

  test-linux:
    needs: build-linux
    runs-on: self-hosted
    steps:
      - run: |
          wget https://github.com/gondiaz/WCSimDataTools/releases/download/CI_release/Archive.zip
          unzip Archive.zip
          python -m unittest discover -s ./tests  -p 'test_*.py'
        shell: bash -l {0}
      - name: Upload csv files
        uses: actions/upload-artifact@v4
        with:
          name: csv_files
          path: |
            *.csv
