name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: self-hosted
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: wcsimdatatools
#        miniconda-version: "latest"
        environment-file: env.yaml
        python-version: 3.10.3
        auto-activate-base: false
        remove-profiles: false # very important to avoid profiles deletion
    - run: |
        conda info
        conda list
#    - name: Lint with flake8
#      run: |
#        conda install flake8
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install package
      run: |
        pip install .

  test-linux:
    needs: build-linux
    runs-on: self-hosted
    steps:
      - run: |
          python -m unittest discover -s ./tests  -p 'test_*.py'
